### ISSUE TITLE
ไม่ได้มีปัญหากับ repo แต่มีปัญหากับเจ้าของ account

### ISSUE THREAD

**Issue by netchanokmu** [SanyaTangook/Reacr-Projact#1]
![chipi-chipi-chapa-chapa](https://github.com/SanyaTangook/Reacr-Projact/assets/120549068/fa9c7021-e123-496f-b27c-e184aeb7b8e2)

**Comment by SanyaTangook** [comment]
"ขอบคุณที่แจ้งให้ทราบ" **ทำหน้ามองบน

**Comment by netchanokmu** [comment]
sorry eiei
